# Generated by Django 2.1.7 on 2019-03-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_restaurant_list',
            field=models.ManyToManyField(to='campus.Restaurant'),
        ),
    ]
