# Generated by Django 2.2 on 2019-04-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='items',
            new_name='item_list',
        ),
    ]
