# Generated by Django 2.2 on 2019-04-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_auto_20190404_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='friday',
            field=models.CharField(default='8AM - 10PM', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='monday',
            field=models.CharField(default='8AM - 10PM', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default='(xxx) xxx-xxxx', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='saturday',
            field=models.CharField(default='8AM - 10PM', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sunday',
            field=models.CharField(default='8AM - 10PM', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thursday',
            field=models.CharField(default='8AM - 10PM', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tuesday',
            field=models.CharField(default='8AM - 10PM', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wednesday',
            field=models.CharField(default='8AM - 10PM', max_length=20),
        ),
    ]
