# Generated by Django 2.1.7 on 2019-04-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_auto_20190418_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='No description added', max_length=300),
        ),
    ]
