# Generated by Django 2.1.7 on 2019-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='No description', max_length=100),
        ),
    ]
