# Generated by Django 2.1.7 on 2019-04-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_auto_20190422_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_restaurant_list',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
