# Generated by Django 2.2 on 2019-04-25 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus', '0013_auto_20190422_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='maintainer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='friday',
            field=models.CharField(default='8:00AM - 10:00PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='monday',
            field=models.CharField(default='8:00AM - 10:00PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='saturday',
            field=models.CharField(default='8:00AM - 10:00PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sunday',
            field=models.CharField(default='8:00AM - 10:00PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thursday',
            field=models.CharField(default='8:00AM - 10:00PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tuesday',
            field=models.CharField(default='8:00AM - 10:00PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wednesday',
            field=models.CharField(default='8:00AM - 10:00PM', max_length=20),
        ),
    ]
